[package]
name = "operon-core"
version.workspace = true
edition.workspace = true

[dependencies]
axum.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tower-http.workspace = true
tower.workspace = true
http-body-util.workspace = true
jsonwebtoken.workspace = true
rand.workspace = true
sha2.workspace = true
hex.workspace = true
uuid.workspace = true
anyhow.workspace = true
thiserror.workspace = true
aws-config = "1.10.1"
aws-sdk-ssm = "1.118.0"
bytes = "1.12.1"
http = "1.5.0"
ed25519-dalek = "2"
base64 = "0.23.1"
async-trait = "0.1.92"
